export enum IconNameEnum {
    ArrowUp = 'ArrowUp',
    ArrowDown = 'ArrowDown',
    ArrowRight = 'ArrowRight',
    ArrowLeft = 'ArrowLeft',
    LoveArrowLeftIcon = 'LoveArrowLeftIcon',
    LoveArrowRightIcon = 'LoveArrowRightIcon',
    ErrorIcon = 'ErrorIcon',
    SeenIcon = 'SeenIcon',
    SendingIcon = 'SendingIcon',
    SentIcon = 'SentIcon',
    CloseCircleIcon = 'CloseCircleIcon',
    WifiOffIcon = 'WifiOffIcon',
    StoryIcon = 'StoryIcon',
    SettingIcon = 'SettingIcon',
    ChatIcon = 'ChatIcon',
    SendIcon = 'SendIcon',
    DarkModeIcon = 'DarkModeIcon',
    LanguageIcon = 'LanguageIcon',
    NotificationIcon = 'NotificationIcon',
    CheckIcon = 'CheckIcon',
}
