export enum AppThemeEnum {
    light = 'light',
    dark = 'dark',
    system = 'system',
}

export const Themes = {
    dark: {
        type: 'dark',
        background: '#0A1D37',
        primary: '#F2E5E5',
        text: '#F2E5E5',
        error: '#E94560',
        backButton: '#0A1D37',
        topBarBackground: '#F2E5E5',
        topBarHeaderTextColor: '#C7BCA1',
        arrow: '#0A1D37',
        indicator: '#F2E5E5',
        selectedIcon: '#0A1D37',
        unSelectedIcon: '#354259',
        unSelectedText: '#968C83',
        switchCircle: '#F2E5E5',
    },
    light: {
        type: 'light',
        background: '#FFFFFF',
        primary: '#9182C4',
        text: '#0A1D37',
        error: '#E94560',
        backButton: '#FFFFFF',
        topBarBackground: '#9182C4',
        topBarHeaderTextColor: '#060930',
        arrow: '#FFFFFF',
        indicator: '#EEEEEE',
        selectedIcon: '#FFFFFF',
        unSelectedIcon: '#F7F7F7',
        unSelectedText: '#968C83',
        switchCircle: '#DDE7F2',
    },
} as Record<ThemeKey, Theme>;
