fastlane_version '2.71.0'
fastlane_require 'json'

skip_docs

lane :build_icon do
    appicon(
      appicon_image_file: 'assets/release/ios/app_icon.png',
      appicon_devices: %i[iphone ios_marketing],
      appicon_path: 'ios/Images.xcassets'
    )

    android_appicon(
        appicon_image_file: 'assets/release/android/app_icon.png',
        appicon_icon_types: [:launcher],
        appicon_path: 'android/app/src/main/res/mipmap'
      )
end

