name: github-release
on:
    push:
        tags:
            - v[0-9]+.[0-9]+.[0-9]+*

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - name: ci/checkout-repo
              uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
            - name: ci/test
              uses: ./.github/actions/test

    build-ios-unsigned:
        runs-on: macos-12
        needs:
            - test
        steps:
            - name: ci/checkout-repo
              uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

            - name: ci/prepare-ios-build
              uses: ./.github/actions/prepare-ios-build

            - name: ci/output-ssh-private-key
              shell: bash
              run: |
                  SSH_KEY_PATH=~/.ssh/id_ed25519
                  mkdir -p ~/.ssh
                  echo -e '${{ secrets.SSH_PRIVATE_KEY }}' > ${SSH_KEY_PATH}
                  chmod 0600 ${SSH_KEY_PATH}
                  ssh-keygen -y -f ${SSH_KEY_PATH} > ${SSH_KEY_PATH}.pub

            - name: ci/build-ios-unsigned
              env:
                  TAG: '${{ github.ref_name }}'
                  GITHUB_TOKEN: '${{ secrets.MOBILE_GITHUB_TOKEN }}'
              run: bundle exec fastlane ios unsigned

            - name: ci/upload-ios-unsigned
              uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
              with:
                  name: ios-build-unsigned-${{ github.run_id }}
                  path: '*.ipa'

    build-android-unsigned:
        runs-on: ubuntu-22.04
        needs:
            - test
        steps:
            - name: ci/checkout-repo
              uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

            - name: ci/prepare-android-build
              uses: ./.github/actions/prepare-android-build
              with:
                  sign: false

            - name: ci/build-android-beta
              env:
                  TAG: '${{ github.ref_name }}'
                  GITHUB_TOKEN: '${{ secrets.MOBILE_GITHUB_TOKEN }}'
              run: bundle exec fastlane android unsigned

            - name: ci/upload-android-unsigned-build
              uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
              with:
                  name: android-build-unsigned-${{ github.run_id }}
                  path: '*.apk'

    release:
        runs-on: ubuntu-22.04
        needs:
            - build-ios-unsigned
            - build-android-unsigned
        steps:
            - name: ci/checkout-repo
              uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

            - uses: ruby/setup-ruby@9669f3ee51dc3f4eda8447ab696b3ab19a90d14b # v1.144.0
              with:
                  ruby-version: '2.7.6'

            - name: release/setup-fastlane-dependencies
              run: bundle install
              working-directory: ./fastlane

            - name: ci/download-artifacts
              uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2

            - name: release/create-github-release
              env:
                  TAG: '${{ github.ref_name }}'
                  GITHUB_REF_NAME: '${{ github.ref_name }}'
                  GITHUB_TOKEN: '${{ secrets.MOBILE_GITHUB_TOKEN }}'
              run: bundle exec fastlane github
              working-directory: ./fastlane
